### ISSUE TITLE
Keras "object() doesn't take any parameter" error

### ISSUE THREAD

**Issue by dhruvparamhans** [vsl9/Sentiment-Analysis-with-Convolutional-Networks#1]
Hi there, 

I was just trying to implement your model and I ran into trouble trying to run the CNN using Keras. When I run model.compile with the parameters you provide i get the following error 

     TypeError                                 Traceback (most recent call last)
    <ipython-input-24-8079df85a0aa> in <module>()
    ----> 1 model.compile(loss='categorical_crossentropy', optimizer='adadelta')

    D:\Users\Dhruv.Sharma\AppData\Local\Continuum\Anaconda\lib\site-packages\keras-0.1.2-py2.7.egg\keras\models.pyc in compile(self, optimizer, loss, class_mode, theano_mode)
    332         for r in self.regularizers:
    333             train_loss = r(train_loss)
    --> 334         updates = self.optimizer.get_updates(self.params, self.constraints, train_loss)
    335 
    336         if type(self.X_train) == list:

    D:\Users\Dhruv.Sharma\AppData\Local\Continuum\Anaconda\lib\site-packages\keras-0.1.2-py2.7.egg\keras\optimizers.pyc in get_updates(self, params, constraints, loss)
    138 
    139             new_p = p - self.lr * update
    --> 140             updates.append((p, c(new_p))) # apply constraints
    141 
    142             # update delta_accumulator

    TypeError: object() takes no parameters

**Comment by vsl9** [comment]
Hi Dhruv,
Thanks for reporting the issue.
I developed the original model using Keras 0.1.1.

Now, unitnorm constraint syntax has changed.
So I've updated the notebook to support Keras 0.1.2.
Please fetch the latest commit: 
https://github.com/vsl9/Sentiment-Analysis-with-Convolutional-Networks/commit/e94b0490e81b327fff39dc1aaf7b778aff980d49
