### ISSUE TITLE
Thanks, how to update to the latest keras?

### ISSUE THREAD

**Issue by StevenLOL** [vsl9/Sentiment-Analysis-with-Convolutional-Networks#3]
Seems keras changed a lot,  need to change the code as well.

**Comment by vsl9** [comment]
Yes, Keras API has been changed in order to simplify things and to infer tensor shapes.
I updated the code to support Keras 1.0.3. Please see https://github.com/vsl9/Sentiment-Analysis-with-Convolutional-Networks/commit/6d2c6319916ce782ee18b45482d1f8577321c5a6.
