### ISSUE TITLE
Keras reshape error

### ISSUE THREAD

**Issue by flyingpiglet** [vsl9/Sentiment-Analysis-with-Convolutional-Networks#4]
Seems like the line "**model.add(Reshape(1, conv_input_height, conv_input_width))**" no longer works. It throws an error: 
**** 
TypeError                                 Traceback (most recent call last)
<ipython-input-55-2303074f7694> in <module>()
     26 # Reshape word vectors from Embedding to tensor format suitable for Convolutional layer
     27 # reshape from three dimensional to four dimensional
---> 28 model.add(Reshape(1,conv_input_height, conv_input_width) )
     29 
     30 # first convolutional layer

TypeError: __init__() takes exactly 2 arguments (4 given)
*** 

Based on the Keras documentation, I changed it to: 
model.add(Reshape((1, conv_input_height, conv_input_width)))

And yet it throws another error now: 

****** 
     34 def _prod(a, axis=None, dtype=None, out=None, keepdims=False):
---> 35     return umr_prod(a, axis, dtype, out, keepdims)
     36 
     37 def _any(a, axis=None, dtype=None, out=None, keepdims=False):

TypeError: long() argument must be a string or a number, not 'NoneType'
****** 

I have upgraded both keras/theano to the bleeding edge version. It's been very hard to find any alternative working example of embedding followed by 2d convolution with keras. Any idea why this happens and how we may fix it? 

Thanks a lot!!!

**Comment by ahmedmn** [comment]
Yes, the same error , any updates??

**Comment by flyingpiglet** [comment]
Hey,

Check this out:
https://github.com/fchollet/keras/issues/2812#issuecomment-221860970

Good luck! :)

**Comment by vsl9** [comment]
Keras is a great Deep Learning framework. But recently many changes to API were introduced in order to make code simpler and to allow automatic tensor shapes inference.
I updated the project to support Keras 1.0.3 (with Theano 0.8.2). Please have a look at https://github.com/vsl9/Sentiment-Analysis-with-Convolutional-Networks/commit/6d2c6319916ce782ee18b45482d1f8577321c5a6.
