### ISSUE TITLE
'list' object has no attribute 'min'

### ISSUE THREAD

**Issue by chou1986** [vsl9/Sentiment-Analysis-with-Convolutional-Networks#5]
Hello, i'm trying the code and i found an error that i can not fix in file "Train CNN IMDB.ipynb": 

Traceback (most recent call last):
  File "/home/ch//Sandbox/keras/kaggle_sentAnalysis/cnn_kaggle.py", line 136, in <module>
    output = model.predict_proba(val_X, batch_size=10, verbose=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 791, in predict_proba
    if preds.min() < 0. or preds.max() > 1.:
AttributeError: 'list' object has no attribute 'min'

Thank you.

**Comment by vsl9** [comment]
Hello, can you please check what versions of Keras and Theano do you have? Or did you test with TensorFlow backend? The error description says that Keras model returns a list object while it should be a numpy array. But I wasn't able to reproduce it.
I checked with the latest Keras (1.2.0) and Theano (0.8.2) and the only error I got was "OverflowError: Range exceeds valid bounds". It was connected with default Keras tensor dimensions ordering. I fixed it with a new commit.

**Comment by vsl9** [comment]
Please feel free to re-open the issue if the problem persists.
